"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n%+!u9l-stc06c-rgj(vwhvmr#hkco1$hc3(#nk4ibgls9f69h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [

     # Third-party Apps
    'jazzmin',
    'rest_framework',
    'rest_framework_simplejwt',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local Apps
    'my_app.apps.MyAppConfig',
    
]

# Custom User Model
AUTH_USER_MODEL = 'my_app.BankUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

#Time zone and language settings    

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Kampala'

USE_I18N = True

USE_TZ = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

ALLOCATION_CONFIG = {
    "ENFORCEMENT_MODE": os.getenv("ALLOCATION_ENFORCEMENT_MODE", "balanced"),
    "ENFORCEMENT_POLICY": os.getenv("ALLOCATION_ENFORCEMENT_POLICY", "enforce_high_priority"),
    "DEFAULT_STRATEGY": os.getenv("ALLOCATION_DEFAULT_STRATEGY", "automatic"),
    "HIGH_PRIORITY_LEVELS": ["High", "CRITICAL", "Critical"],
    "CRITICAL_PRIORITY_LEVELS": ["CRITICAL", "Critical"],
}

# Jazzmin Configuration
JAZZMIN_SETTINGS = {
    "site_title": "Centenary Bank Admin",
    "site_header": "Centenary Bank - Allocation Management System",
    "site_brand": "CBAS",
    "welcome_sign": "Welcome to Centenary Bank Allocation System",
    "copyright": "Centenary Bank Uganda Limited",
    
    # UI configuration
    "show_ui_builder": True,
    "ui_tweaks": {
        "sidebar_disable_auto_collapse": False,
        "account_model": "auth.user"
    },
    
    # Dashboard configuration
    "dashboard_sidebarclasses": "sidebar-dark-primary",
    "order_with_respect_to": [
        "my_app.bankuser",
        "my_app.branch", 
        "my_app.auctioneer",
        "my_app.recoverycase",
        "my_app.allocation",
        "my_app.notification",
        "my_app.auditlog",
    ],
    
    # Search configuration
    "search_model": "auth.user",
    "user_avatar": None,
    
    # Navigation configuration
    "navigation": {
        "System Management": {
            "icon": "fas fa-cogs",
            "models": [
                {
                    "name": "bankuser",
                    "app": "my_app",
                    "icon": "fas fa-user-shield",
                    "permissions": ["my_app.change_bankuser", "my_app.view_bankuser"]
                },
            ],
        },
        "Bank Administration": {
            "icon": "fas fa-university",
            "models": [
                {
                    "name": "branch",
                    "app": "my_app",
                    "icon": "fas fa-code-branch"
                },
            ],
        },
        "Auctioneer Management": {
            "icon": "fas fa-gavel",
            "models": [
                {
                    "name": "auctioneer",
                    "app": "my_app",
                    "icon": "fas fa-person-booth"
                },
            ],
        },
        "Recovery Cases": {
            "icon": "fas fa-briefcase",
            "models": [
                {
                    "name": "recoverycase",
                    "app": "my_app",
                    "icon": "fas fa-file-invoice"
                },
                {
                    "name": "allocation",
                    "app": "my_app",
                    "icon": "fas fa-tasks"
                },
            ],
        },
        "System Activity": {
            "icon": "fas fa-history",
            "models": [
                {
                    "name": "notification",
                    "app": "my_app",
                    "icon": "fas fa-bell"
                },
                {
                    "name": "auditlog",
                    "app": "my_app",
                    "icon": "fas fa-clipboard-list"
                },
            ],
        },
    },
    
    # Styling
    "theme": {
        "primaryColor": "#1e40af",  # Bank Blue
        "secondaryColor": "#0369a1",
        "accentColor": "#f59e0b",  # Gold accent
    },
    
    # Icons configuration
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "my_app.BankUser": "fas fa-user-shield",
        "my_app.Branch": "fas fa-code-branch",
        "my_app.Auctioneer": "fas fa-gavel",
        "my_app.RecoveryCase": "fas fa-briefcase",
        "my_app.Allocation": "fas fa-tasks",
        "my_app.Notification": "fas fa-bell",
        "my_app.AuditLog": "fas fa-history",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark-primary",
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_disable_auto_collapse": False,
    "body_bg": "#ecf0f5",
    "content_padding": "10px",
    "search_elevation": 4,
    "navbar_padd": "10px",
    "list_filter_dropdown": True,
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle-o",
}


