# Generated by Django 6.0.7 on 2026-07-25 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=10, unique=True)),
                ('branch_name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('Central', 'Central'), ('Eastern', 'Eastern'), ('Northern', 'Northern'), ('Western', 'Western')], max_length=20)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['branch_name'],
            },
        ),
        migrations.AddField(
            model_name='bankuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='my_app.branch'),
        ),
    ]
