# Generated by Django 6.0.7 on 2026-07-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_branch_bankuser_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctioneer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, unique=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('region', models.CharField(choices=[('Central', 'Central'), ('Eastern', 'Eastern'), ('Northern', 'Northern'), ('Western', 'Western')], max_length=20)),
                ('office_address', models.TextField()),
                ('current_workload', models.PositiveIntegerField(default=0, help_text='Current number of active recovery cases.')),
                ('status', models.BooleanField(default=True, help_text='Uncheck to deactivate the auctioneer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auctioneer',
                'verbose_name_plural': 'Auctioneers',
                'ordering': ['company_name'],
            },
        ),
    ]
