# Generated by Django 6.0.7 on 2026-07-25 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auctioneer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('loan_account_number', models.CharField(max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('national_id', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('collateral_type', models.CharField(choices=[('Land', 'Land'), ('Motor Vehicle', 'Motor Vehicle'), ('Building', 'Building'), ('Household Property', 'Household Property'), ('Machinery', 'Machinery'), ('Other', 'Other')], max_length=30)),
                ('collateral_description', models.TextField()),
                ('collateral_location', models.TextField()),
                ('arrears_days', models.PositiveIntegerField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Allocated', 'Allocated'), ('In Recovery', 'In Recovery'), ('Recovered', 'Recovered'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recovery_stage', models.CharField(choices=[('Demand Notice', 'Demand Notice'), ('Legal Review', 'Legal Review'), ('Auctioneer Assignment', 'Auctioneer Assignment'), ('Asset Recovery', 'Asset Recovery'), ('Case Closed', 'Case Closed')], default='Demand Notice', max_length=30)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_cases', to='my_app.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_recovery_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recovery Case',
                'verbose_name_plural': 'Recovery Cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
