# Generated by Django 6.0.7 on 2026-08-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_add_system_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='role',
            field=models.CharField(choices=[('LOAN_OFFICER_BRANCH', 'Loan Officer Branch'), ('CREDIT_OFFICER_H/O', 'Credit Officer H/O'), ('SYSTEM_ADMIN', 'System Admin'), ('SUPER_ADMIN', 'Super Admin')], max_length=20),
        ),
    ]
