/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAllocationRouteImport } from './routes/admin.allocation'
import { Route as AdminAuctioneersRouteImport } from './routes/admin.auctioneers'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCasesRouteImport } from './routes/admin.cases'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminTransactionLimitsRouteImport } from './routes/admin.transaction-limits'
import { Route as CreditIndexRouteImport } from './routes/credit.index'
import { Route as CreditAllocationRouteImport } from './routes/credit.allocation'
import { Route as CreditCasesRouteImport } from './routes/credit.cases'
import { Route as CreditSettingsRouteImport } from './routes/credit.settings'
import { Route as CreditSupportRouteImport } from './routes/credit.support'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as OfficerCasesRouteImport } from './routes/officer.cases'
import { Route as OfficerSettingsRouteImport } from './routes/officer.settings'
import { Route as OfficerSupportRouteImport } from './routes/officer.support'
import { Route as OfficerWorkspaceRouteImport } from './routes/officer.workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAllocationRoute = AdminAllocationRouteImport.update({
  id: '/admin/allocation',
  path: '/admin/allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuctioneersRoute = AdminAuctioneersRouteImport.update({
  id: '/admin/auctioneers',
  path: '/admin/auctioneers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/admin/cases',
  path: '/admin/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionLimitsRoute = AdminTransactionLimitsRouteImport.update({
  id: '/admin/transaction-limits',
  path: '/admin/transaction-limits',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditIndexRoute = CreditIndexRouteImport.update({
  id: '/credit/',
  path: '/credit/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditAllocationRoute = CreditAllocationRouteImport.update({
  id: '/credit/allocation',
  path: '/credit/allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditCasesRoute = CreditCasesRouteImport.update({
  id: '/credit/cases',
  path: '/credit/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditSettingsRoute = CreditSettingsRouteImport.update({
  id: '/credit/settings',
  path: '/credit/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditSupportRoute = CreditSupportRouteImport.update({
  id: '/credit/support',
  path: '/credit/support',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/officer/',
  path: '/officer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerCasesRoute = OfficerCasesRouteImport.update({
  id: '/officer/cases',
  path: '/officer/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerSettingsRoute = OfficerSettingsRouteImport.update({
  id: '/officer/settings',
  path: '/officer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerSupportRoute = OfficerSupportRouteImport.update({
  id: '/officer/support',
  path: '/officer/support',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerWorkspaceRoute = OfficerWorkspaceRouteImport.update({
  id: '/officer/workspace',
  path: '/officer/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/auctioneers': typeof AdminAuctioneersRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/transaction-limits': typeof AdminTransactionLimitsRoute
  '/credit/allocation': typeof CreditAllocationRoute
  '/credit/cases': typeof CreditCasesRoute
  '/credit/settings': typeof CreditSettingsRoute
  '/credit/support': typeof CreditSupportRoute
  '/officer/cases': typeof OfficerCasesRoute
  '/officer/settings': typeof OfficerSettingsRoute
  '/officer/support': typeof OfficerSupportRoute
  '/officer/workspace': typeof OfficerWorkspaceRoute
  '/admin/': typeof AdminIndexRoute
  '/credit/': typeof CreditIndexRoute
  '/officer/': typeof OfficerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/auctioneers': typeof AdminAuctioneersRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/transaction-limits': typeof AdminTransactionLimitsRoute
  '/credit/allocation': typeof CreditAllocationRoute
  '/credit/cases': typeof CreditCasesRoute
  '/credit/settings': typeof CreditSettingsRoute
  '/credit/support': typeof CreditSupportRoute
  '/officer/cases': typeof OfficerCasesRoute
  '/officer/settings': typeof OfficerSettingsRoute
  '/officer/support': typeof OfficerSupportRoute
  '/officer/workspace': typeof OfficerWorkspaceRoute
  '/admin': typeof AdminIndexRoute
  '/credit': typeof CreditIndexRoute
  '/officer': typeof OfficerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/auctioneers': typeof AdminAuctioneersRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/transaction-limits': typeof AdminTransactionLimitsRoute
  '/credit/allocation': typeof CreditAllocationRoute
  '/credit/cases': typeof CreditCasesRoute
  '/credit/settings': typeof CreditSettingsRoute
  '/credit/support': typeof CreditSupportRoute
  '/officer/cases': typeof OfficerCasesRoute
  '/officer/settings': typeof OfficerSettingsRoute
  '/officer/support': typeof OfficerSupportRoute
  '/officer/workspace': typeof OfficerWorkspaceRoute
  '/admin/': typeof AdminIndexRoute
  '/credit/': typeof CreditIndexRoute
  '/officer/': typeof OfficerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/admin/allocation'
    | '/admin/auctioneers'
    | '/admin/audit'
    | '/admin/cases'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/transaction-limits'
    | '/credit/allocation'
    | '/credit/cases'
    | '/credit/settings'
    | '/credit/support'
    | '/officer/cases'
    | '/officer/settings'
    | '/officer/support'
    | '/officer/workspace'
    | '/admin/'
    | '/credit/'
    | '/officer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/admin/allocation'
    | '/admin/auctioneers'
    | '/admin/audit'
    | '/admin/cases'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/transaction-limits'
    | '/credit/allocation'
    | '/credit/cases'
    | '/credit/settings'
    | '/credit/support'
    | '/officer/cases'
    | '/officer/settings'
    | '/officer/support'
    | '/officer/workspace'
    | '/admin'
    | '/credit'
    | '/officer'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/admin/allocation'
    | '/admin/auctioneers'
    | '/admin/audit'
    | '/admin/cases'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/transaction-limits'
    | '/credit/allocation'
    | '/credit/cases'
    | '/credit/settings'
    | '/credit/support'
    | '/officer/cases'
    | '/officer/settings'
    | '/officer/support'
    | '/officer/workspace'
    | '/admin/'
    | '/credit/'
    | '/officer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAllocationRoute: typeof AdminAllocationRoute
  AdminAuctioneersRoute: typeof AdminAuctioneersRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCasesRoute: typeof AdminCasesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTransactionLimitsRoute: typeof AdminTransactionLimitsRoute
  CreditAllocationRoute: typeof CreditAllocationRoute
  CreditCasesRoute: typeof CreditCasesRoute
  CreditSettingsRoute: typeof CreditSettingsRoute
  CreditSupportRoute: typeof CreditSupportRoute
  OfficerCasesRoute: typeof OfficerCasesRoute
  OfficerSettingsRoute: typeof OfficerSettingsRoute
  OfficerSupportRoute: typeof OfficerSupportRoute
  OfficerWorkspaceRoute: typeof OfficerWorkspaceRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CreditIndexRoute: typeof CreditIndexRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/allocation': {
      id: '/admin/allocation'
      path: '/admin/allocation'
      fullPath: '/admin/allocation'
      preLoaderRoute: typeof AdminAllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auctioneers': {
      id: '/admin/auctioneers'
      path: '/admin/auctioneers'
      fullPath: '/admin/auctioneers'
      preLoaderRoute: typeof AdminAuctioneersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/admin/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transaction-limits': {
      id: '/admin/transaction-limits'
      path: '/admin/transaction-limits'
      fullPath: '/admin/transaction-limits'
      preLoaderRoute: typeof AdminTransactionLimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit/': {
      id: '/credit/'
      path: '/credit'
      fullPath: '/credit/'
      preLoaderRoute: typeof CreditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit/allocation': {
      id: '/credit/allocation'
      path: '/credit/allocation'
      fullPath: '/credit/allocation'
      preLoaderRoute: typeof CreditAllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit/cases': {
      id: '/credit/cases'
      path: '/credit/cases'
      fullPath: '/credit/cases'
      preLoaderRoute: typeof CreditCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit/settings': {
      id: '/credit/settings'
      path: '/credit/settings'
      fullPath: '/credit/settings'
      preLoaderRoute: typeof CreditSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit/support': {
      id: '/credit/support'
      path: '/credit/support'
      fullPath: '/credit/support'
      preLoaderRoute: typeof CreditSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/': {
      id: '/officer/'
      path: '/officer'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/cases': {
      id: '/officer/cases'
      path: '/officer/cases'
      fullPath: '/officer/cases'
      preLoaderRoute: typeof OfficerCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/settings': {
      id: '/officer/settings'
      path: '/officer/settings'
      fullPath: '/officer/settings'
      preLoaderRoute: typeof OfficerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/support': {
      id: '/officer/support'
      path: '/officer/support'
      fullPath: '/officer/support'
      preLoaderRoute: typeof OfficerSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/workspace': {
      id: '/officer/workspace'
      path: '/officer/workspace'
      fullPath: '/officer/workspace'
      preLoaderRoute: typeof OfficerWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAllocationRoute: AdminAllocationRoute,
  AdminAuctioneersRoute: AdminAuctioneersRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCasesRoute: AdminCasesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTransactionLimitsRoute: AdminTransactionLimitsRoute,
  CreditAllocationRoute: CreditAllocationRoute,
  CreditCasesRoute: CreditCasesRoute,
  CreditSettingsRoute: CreditSettingsRoute,
  CreditSupportRoute: CreditSupportRoute,
  OfficerCasesRoute: OfficerCasesRoute,
  OfficerSettingsRoute: OfficerSettingsRoute,
  OfficerSupportRoute: OfficerSupportRoute,
  OfficerWorkspaceRoute: OfficerWorkspaceRoute,
  AdminIndexRoute: AdminIndexRoute,
  CreditIndexRoute: CreditIndexRoute,
  OfficerIndexRoute: OfficerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
